source = /home/nora/.config/hypr/latte.conf
$accent = $mauve
$accentAlpha = $mauveAlpha
$font = JetBrainsMono Nerd Font

general {
  hide_cursor = true
}

background {
  monitor =
  path = ~/.config/background
  blur_passes = 0
}

label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = 0, -30
  halign = center
  valign = top
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 $USER</i></span>
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, 0
  halign = center
  valign = center
}
